name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: ci
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Clone vs-control repository
        uses: actions/checkout@v3
        with:
          path: vs-control

      - name: Clone vs-core-kt repository
        uses: actions/checkout@v3
        with:
          repository: VladislavSumin/vs-core-kt
          path: vs-core-kt

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Run gradle
        working-directory: ./vs-control

        run: >-
          ./gradlew
          :ci
          --no-daemon
          --stacktrace