name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: macos-12
    timeout-minutes: 20
    steps:
      - name: Clone vs-control repository
        uses: actions/checkout@v3
        with:
          path: vs-control

      - name: Clone vs-core-kt repository
        uses: actions/checkout@v3
        with:
          repository: VladislavSumin/vs-core-kt
          path: vs-core-kt

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Run gradle
        working-directory: ./vs-control

        run: >-
          ./gradlew
          -Pru.vs.core.ci=true
          -Pru.vs.core.ci.github=true
          :ci
          --no-daemon
          --stacktrace

      - name: Upload android client debug
        uses: actions/upload-artifact@v3
        with:
          name: android-client-debug
          path: "vs-control/client/android/build/outputs/apk/debug/**.apk"
          if-no-files-found: error

      - name: Upload android client release
        uses: actions/upload-artifact@v3
        with:
          name: android-client-release
          path: "vs-control/client/android/build/outputs/apk/release/**.apk"
          if-no-files-found: error

      - name: Upload jvm client
        uses: actions/upload-artifact@v3
        with:
          name: jvm-client
          path: "vs-control/client/jvm/build/libs/**.jar"
          if-no-files-found: error

      - name: Upload jvm server
        uses: actions/upload-artifact@v3
        with:
          name: jvm-server
          path: "vs-control/server/jvm/build/libs/**.jar"
          if-no-files-found: error
